set_project("HoshinoEngine")

add_cxflags("/utf-8")
add_rules("mode.debug", "mode.releasedbg", "mode.release", "mode.minsizerel")
set_arch("x64")
-- add_cxxflags("-Wall")
set_languages("c++20")
add_requires("glfw", "glm","vulkansdk","glad","spdlog","magic_enum") 
add_requires("imgui v1.91.8-docking",{configs = {glfw = true}})
includes("src/Hoshino","src/Client")