#pragma once
#include "HoshinoMin.h"
#include <nvrhi/nvrhi.h>

namespace Hoshino
{
	enum class TextureFormat : uint8_t
	{
		Unknown = 0,
		R8_UINT = static_cast<uint8_t>(nvrhi::Format::R8_UINT),
		R8_SINT = static_cast<uint8_t>(nvrhi::Format::R8_SINT),
		R8_UNORM = static_cast<uint8_t>(nvrhi::Format::R8_UNORM),
		R8_SNORM = static_cast<uint8_t>(nvrhi::Format::R8_SNORM),
		RG8_UINT = static_cast<uint8_t>(nvrhi::Format::RG8_UINT),
		RG8_SINT = static_cast<uint8_t>(nvrhi::Format::RG8_SINT),
		RG8_UNORM = static_cast<uint8_t>(nvrhi::Format::RG8_UNORM),
		RG8_SNORM = static_cast<uint8_t>(nvrhi::Format::RG8_SNORM),
		R16_UINT = static_cast<uint8_t>(nvrhi::Format::R16_UINT),
		R16_SINT = static_cast<uint8_t>(nvrhi::Format::R16_SINT),
		R16_UNORM = static_cast<uint8_t>(nvrhi::Format::R16_UNORM),
		R16_SNORM = static_cast<uint8_t>(nvrhi::Format::R16_SNORM),
		R16_FLOAT = static_cast<uint8_t>(nvrhi::Format::R16_FLOAT),
		BGRA4_UNORM = static_cast<uint8_t>(nvrhi::Format::BGRA4_UNORM),
		B5G6R5_UNORM = static_cast<uint8_t>(nvrhi::Format::B5G6R5_UNORM),
		B5G5R5A1_UNORM = static_cast<uint8_t>(nvrhi::Format::B5G5R5A1_UNORM),
		RGBA8_UINT = static_cast<uint8_t>(nvrhi::Format::RGBA8_UINT),
		RGBA8_SINT = static_cast<uint8_t>(nvrhi::Format::RGBA8_SINT),
		RGBA8_UNORM = static_cast<uint8_t>(nvrhi::Format::RGBA8_UNORM),
		RGBA8_SNORM = static_cast<uint8_t>(nvrhi::Format::RGBA8_SNORM),
		BGRA8_UNORM = static_cast<uint8_t>(nvrhi::Format::BGRA8_UNORM),
		SRGBA8_UNORM = static_cast<uint8_t>(nvrhi::Format::SRGBA8_UNORM),
		SBGRA8_UNORM = static_cast<uint8_t>(nvrhi::Format::SBGRA8_UNORM),
		R10G10B10A2_UNORM = static_cast<uint8_t>(nvrhi::Format::R10G10B10A2_UNORM),
		R11G11B10_FLOAT = static_cast<uint8_t>(nvrhi::Format::R11G11B10_FLOAT),
		RG16_UINT = static_cast<uint8_t>(nvrhi::Format::RG16_UINT),
		RG16_SINT = static_cast<uint8_t>(nvrhi::Format::RG16_SINT),
		RG16_UNORM = static_cast<uint8_t>(nvrhi::Format::RG16_UNORM),
		RG16_SNORM = static_cast<uint8_t>(nvrhi::Format::RG16_SNORM),
		RG16_FLOAT = static_cast<uint8_t>(nvrhi::Format::RG16_FLOAT),
		R32_UINT = static_cast<uint8_t>(nvrhi::Format::R32_UINT),
		R32_SINT = static_cast<uint8_t>(nvrhi::Format::R32_SINT),
		R32_FLOAT = static_cast<uint8_t>(nvrhi::Format::R32_FLOAT),
		RGBA16_UINT = static_cast<uint8_t>(nvrhi::Format::RGBA16_UINT),
		RGBA16_SINT = static_cast<uint8_t>(nvrhi::Format::RGBA16_SINT),
		RGBA16_FLOAT = static_cast<uint8_t>(nvrhi::Format::RGBA16_FLOAT),
		RGBA16_UNORM = static_cast<uint8_t>(nvrhi::Format::RGBA16_UNORM),
		RGBA16_SNORM = static_cast<uint8_t>(nvrhi::Format::RGBA16_SNORM),
		RG32_UINT = static_cast<uint8_t>(nvrhi::Format::RG32_UINT),
		RG32_SINT = static_cast<uint8_t>(nvrhi::Format::RG32_SINT),
		RG32_FLOAT = static_cast<uint8_t>(nvrhi::Format::RG32_FLOAT),
		RGB32_UINT = static_cast<uint8_t>(nvrhi::Format::RGB32_UINT),
		RGB32_SINT = static_cast<uint8_t>(nvrhi::Format::RGB32_SINT),
		RGB32_FLOAT = static_cast<uint8_t>(nvrhi::Format::RGB32_FLOAT),
		RGBA32_UINT = static_cast<uint8_t>(nvrhi::Format::RGBA32_UINT),
		RGBA32_SINT = static_cast<uint8_t>(nvrhi::Format::RGBA32_SINT),
		RGBA32_FLOAT = static_cast<uint8_t>(nvrhi::Format::RGBA32_FLOAT),

		D16 = static_cast<uint8_t>(nvrhi::Format::D16),
		D24S8 = static_cast<uint8_t>(nvrhi::Format::D24S8),
		X24G8_UINT = static_cast<uint8_t>(nvrhi::Format::X24G8_UINT),
		D32 = static_cast<uint8_t>(nvrhi::Format::D32),
		D32S8 = static_cast<uint8_t>(nvrhi::Format::D32S8),
		X32G8_UINT = static_cast<uint8_t>(nvrhi::Format::X32G8_UINT),

		BC1_UNORM = static_cast<uint8_t>(nvrhi::Format::BC1_UNORM),
		BC1_UNORM_SRGB = static_cast<uint8_t>(nvrhi::Format::BC1_UNORM_SRGB),
		BC2_UNORM = static_cast<uint8_t>(nvrhi::Format::BC2_UNORM),
		BC2_UNORM_SRGB = static_cast<uint8_t>(nvrhi::Format::BC2_UNORM_SRGB),
		BC3_UNORM = static_cast<uint8_t>(nvrhi::Format::BC3_UNORM),
		BC3_UNORM_SRGB = static_cast<uint8_t>(nvrhi::Format::BC3_UNORM_SRGB),
		BC4_UNORM = static_cast<uint8_t>(nvrhi::Format::BC4_UNORM),
		BC4_SNORM = static_cast<uint8_t>(nvrhi::Format::BC4_SNORM),
		BC5_UNORM = static_cast<uint8_t>(nvrhi::Format::BC5_UNORM),
		BC5_SNORM = static_cast<uint8_t>(nvrhi::Format::BC5_SNORM),
		BC6H_UFLOAT = static_cast<uint8_t>(nvrhi::Format::BC6H_UFLOAT),
		BC6H_SFLOAT = static_cast<uint8_t>(nvrhi::Format::BC6H_SFLOAT),
		BC7_UNORM = static_cast<uint8_t>(nvrhi::Format::BC7_UNORM),
		BC7_UNORM_SRGB = static_cast<uint8_t>(nvrhi::Format::BC7_UNORM_SRGB),

		COUNT = static_cast<uint8_t>(nvrhi::Format::COUNT)
	};
}