target("HoshinoEngine")   
    set_kind("binary")
    add_files("**.cpp")
    add_includedirs("includes",{public = true})
    add_packages("glfw", "glm","vulkansdk","imgui","glad")
    add_defines("HOSHINO_EXPORTS")