target("HoshinoEngine")   
    set_kind("binary")
    add_files("**.cpp")
    add_includedirs("Public",{public = true})
    add_packages("glfw", "glm","vulkansdk","imgui","glad","spdlog")
    add_defines("HOSHINO_EXPORTS","HOSHINO_ASSERT")
    set_pcxxheader("Public/Core/HoshinoPch.h")