target("Client")   
    set_kind("binary")
    add_files("**.cpp")
    add_includedirs("Public")
    add_packages("glfw", "glm","vulkansdk","imgui","glad","spdlog")
    add_deps("HoshinoEngine","Shader")
    add_links("HoshinoEngine")